apiVersion: v1
kind: Service
metadata:
  name: user-registration
  namespace: user-management
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
spec:
  selector:
    app: user-registration
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
